# Generated by Django 5.1.3 on 2024-11-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personne',
            name='diplome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personne',
            name='ecole',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personne',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10),
        ),
    ]
